#Postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://containers-us-west-176.railway.app:6101/railway
spring.datasource.username=postgres
spring.datasource.password=Ycl32UnSP87lrz4iXAIq
spring.jpa.hibernate.ddl-auto=update