spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-203:railway:app:5594/railway
    username: postgres
    password: qPpR77NjSX8QuyiDqqad
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
#
#logging:
#  level:
#    org.springframework.security: trace

#rsa:
#  private-key: classpath:certs/private.pem
#  public-key: classpath:certs/public.pem







