spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

#logging:
#  level:
#    org.springframework.security: trace

#rsa:
#  private-key: classpath:certs/private.pem
#  public-key: classpath:certs/public.pem







