url: ${PGURL}
user: ${PGUSER}
password: ${PGPASSWORD}

spring:
  datasource:
    url: ${PGURL}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: update