spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./students
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update