#Postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://containers-us-west-38.railway.app:5984/railway
spring.datasource.username=postgres
spring.datasource.password=I6GMTYInniUYbcAn7NB0
spring.jpa.hibernate.ddl-auto=update